app:
  version: 1.0.0
  private-key-base64: $GRANT_N_Z_PRIVATE_KEY
  environment: $GRANT_N_Z_ENV
  log-level: $GRANT_N_Z_LOG_LEVEL
  policy-file-path: $GRANT_N_Z_POLICY_FILE_PATH

db:
  host: $GRANT_N_Z_HOST
  user: $GRANT_N_Z_USER
  password: $GRANT_N_Z_PASSWORD
  port: $GRANT_N_Z_PORT
  db: $GRANT_N_Z_DB
